export const elements = {
    sitesSelector: '#redirect-domain',
    typeSelector: '#redirect-type',
    redirectDescription: '#redirect-description',
    queryStringSelector: "#copyQueryString",
    urlsaText: '#urlsa-redirect',
    urlsbText: '#urlsb-redirect',
    validateBtn: '#validate-btn',
    tableResult: '.table',
    tableRedirectType: '.individual-redirectType',
    tableQueryString: '.individual-checkbox',
    clearButton: '#clear-btn',
    generateButton: '#generate-btn',
    langValidation: '#validate-language',
    ticketContent: '#ticket-content',
    ticketContentSelector: "#ticket-content-selector",
    wuTicket: "#wuTicket",
    themeSwitch: "#theme input",

}